### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by ocots** [control-toolbox/SandboxZenodoOC#1]
@jbcaillau Ce repo est un repo test pour la configuration de Zenodo et du fichier `CITATION.cff`.

 Le fichier `.zenodo.json` permet de configurer les métadonnées qui apparaissent sur Zenodo : https://sandbox.zenodo.org/records/101374

Ce repo envoie sur `sandbox.zenodo.org` qui est un site test. Le vrai site zenodo est 

Il faut mettre à jour le fichier `.zenodo.json` puis quand ce sera bon, on peut mettre à jour celui de OptimalControl.jl.

**Comment by ocots** [comment]
@jbcaillau @PierreMartinon @joseph-gergaud 

Il faut : 

- un titre
- des mots-clés
- une description

**Comment by jbcaillau** [comment]
thanks @ocots for setting this up

> @jbcaillau @PierreMartinon @joseph-gergaud
> 
> Il faut :
> 
> * un titre
OptimalControl.jl: a Julia package to solve optimal control problems

> * des mots-clés

control of ODE's, optimization, direct transcription, shooting

> * une description
(from [OptimalControl.jl](https://github.com/control-toolbox/OptimalControl.jl) README)

The [OptimalControl.jl](https://juliahub.com/ui/Packages/General/OptimalControl) package is the root package of the [control-toolbox ecosystem](https://github.com/control-toolbox). The control-toolbox ecosystem gathers Julia packages for mathematical control and applications. It aims to provide tools to model and solve optimal control problems with ordinary differential equations by direct and indirect methods.

**Comment by ocots** [comment]
Titre : 

**OptimalControl.jl: a Julia package to modelise and solve optimal control problems in the ODE's**

or 

**OptimalControl.jl: a Julia package to modelise and solve optimal control problems in the ordinary differential equations**

or 

**OptimalControl.jl: modelise control system of ODE's and solve optimal control problems in Julia**

**Comment by ocots** [comment]
@jbcaillau @PierreMartinon Please choose a title and I can close this.

**Comment by ocots** [comment]
@jbcaillau Maybe "with ODE's" instead of "in the ODE's".
